version: '3'

services:
  db:
    image: mysql:8.0.36
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'storage'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1111'
      MYSQL_ROOT_PASSWORD: '1111'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: